### ISSUE TITLE
Causes function calls to lose their highlighting

### ISSUE THREAD

**Issue by ComtriS** [abusalimov/SublimeCImproved#11]
Under Monokai and "C" style, function calls are highlighted in blue.  Under Monokai and "C Improved" style, function calls remain white.

**Comment by abusalimov** [comment]
This is the intended behavior. Only special (a.k.a. support) functions are highlighted (like `printf`). Remaining are left as is.

**Comment by ComtriS** [comment]
I see.  Is there some way to change this?  Would be great if there was color settings somewhere.

**Comment by abusalimov** [comment]
Well, customizing syntax definition files is always a pain, I'm afraid the only way is to modify tmLanguage file directly. However, I believe that the current behavior should be left as is, to be consistent with syntax definitions of other languages, and to make the highlighting more informative by emphasizing library functions. So, I'm probably not going to change this, at least in the master.

To be clear, I would likely add an option for a user to be able to customize this, among with other highlighting aspects, if I could. But again, I don't know how to achieve this without doing some magic like generating tmLanguage on the fly.

If the highlighting really annoys you, you could fork the repo and change [the regex](https://github.com/abusalimov/SublimeCImproved/blob/v1.3.3/C%20Improved.tmLanguage#L366-L368) that define a function call:
```
		<key>call</key>
		<dict>
			...
				(?= # don't consume to recognize support functions
				    (?: [A-Za-z_]\w*+ | ::[^:] )++
				    (?:\s|/\*.*?\*/)*+ \( )
```
... to something like this:
```
				((?: [A-Za-z_]\w*+ | ::[^:] )++)
				(?= (?:\s|/\*.*?\*/)*+ \( )
```
And add a pattern capturing that group and associating it, for example, with `support.function.custom.c` scope:
```
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.custom.c</string>
				</dict>
			</dict>
```
This should do the trick!

**Comment by ComtriS** [comment]
Awesome thanks, I'll do that.  You may want to add that to some README or something.

**Comment by abusalimov** [comment]
You're welcome, thanks for reporting this.
OK, I'll consider mentioning the issue in **Dropped features** section of README, and I'll leave this open until I get some spare time to do that.

**Comment by ComtriS** [comment]
Thanks for C Improved. It's very useful!

**Comment by abusalimov** [comment]
Done

**Comment by abusalimov** [comment]
BTW, the default behavior is now reverted to highlight all function calls (as it used to be in the standard C package), so this issue can be considered as fixed.
