### ISSUE TITLE
Syntax highlight fails when function argument is on separate line

### ISSUE THREAD

**Issue by yoonghm** [abusalimov/SublimeCImproved#12]
Markdown can highlight the code correctly but the highlight package from the standard and C-Improved do not work.

```C
int doIt(int a)
{
  //
}
```

```C
int doIt
(int a)
{
  //
}
```

**Comment by abusalimov** [comment]
Hi! Thanks for reporting this. I'm afraid, there is no way to handle this properly, it's tmLanguage syntax limitation: it is possible to parse a source using regular expressions only line-by-line. That is, when parsing `int doIt`, there is no way to look ahead `(int a)` on the next line, and vice versa.

**Comment by abusalimov** [comment]
Duplicates #3
