### ISSUE TITLE
Losing highlighting in numbers, struct members & function calls

### ISSUE THREAD

**Issue by kgizdov** [abusalimov/SublimeCImproved#15]
Hi,

Thank you for a great Sublime package!

First and foremost, I'd like to say that I have read the dropped features section and the referenced issue #11 

Still, however, I would like to put these images (below) for reference and bring up a problem I am having.

![Without C Improved](http://i.imgur.com/rDYQAhL.png)
![With C Improved](http://i.imgur.com/zxhpnbH.png)

Firstly, you will notice that the number at the end (50E12) is recognised normally without C Improved, but it's not recognised without it. I'm not sure if this is because of the sci notation or the * before, however it presents an issue when you have all of these values disappear into the white space.

Secondly, the normal highlighting of struct members really does help coding, especially when you have try to read such arithmetic or long conditionals. Instead of reading everything thoroughly trying to find the exact property in question, highlighting helps one to concentrate only on the important bits. For example, instead of seeing

    if (bodies[i].is_dark || bodies[i].collided || (bodies[i].mass == 0.1)) continue;
    bodies[i].position.x = 2.0 * bodies[i].position.x - bodies[i].old_position.x + ((bodies[i].speed.x) * 50E12);

one sees

    if (is_dark || collided || (mass == 0.1)) continue;
    position.x = 2.0 * position.x - old_position.x + ((speed.x) * 50E12);

Also, as discussed in #11 , the highlighting of function calls could be done manually and the emphasis on built-in functions is a nice thing to have. However, functions that are defined in-file or in referenced custom library are still highlighted, even though with different colour. Could I then propose that function calls for non built-in functions be remapped to a different colour (by expressing them as a different language element or something else more suited). This would help a lot with some of the projects I am working on, where most functions are custom and many of those are almost entirely comprised of custom functions themselves.

The theme I am using is [1337](https://packagecontrol.io/packages/1337%20Color%20Scheme)

I hope I'm not asking too much and you can see how these could benefit the process by improving the visuals.

Thanks.

**Comment by abusalimov** [comment]
Thank you very much for reporting these!

> Firstly, you will notice that the number at the end (50E12) is recognised normally without C Improved, but it's not recognised without it. I'm not sure if this is because of the sci notation or the * before, however it presents an issue when you have all of these values disappear into the white space.
> 
> Secondly, the normal highlighting of struct members really does help coding, especially when you have try to read such arithmetic or long conditionals. Instead of reading everything thoroughly trying to find the exact property in question, highlighting helps one to concentrate only on the important bits.

Both these concerns sound reasonable to me, I'm definitely going to address them when I have some spare time, by the end of the week hopefully.

> However, functions that are defined in-file or in referenced custom library are still highlighted, even though with different colour.

I'm not quite sure that I got it. Do you mean the built-in Sublime C package? I've just checked C Improve, and there's only `meta.function-call.c` scope.

Anyway, your arguments on this also make sense to me. I'm coming to realize now that the default `support.function.any-method.c` scope for calls of rest functions was not that bad, after all. In fact, I've just noticed, that some color schemes even have different styling of calls to the set of recognized functions and calls to custom functions (`any-method`). I guess, you could even propose a PR to developers of 1337 after that, e.g. making calls to custom functions the same color as for library ones, but, say, _italic_. Or vice versa, like in the following example in a [related SO answer](http://stackoverflow.com/questions/11978816/highlight-function-calls-sublime-text-python/12030602#12030602):

![](http://i.stack.imgur.com/9Zs8n.png)

**Comment by kgizdov** [comment]
Thanks for taking the time.

For the function calls - Yes, that looks like a solid way of doing it and if you think that's best and doing go for it.

What I was referring to, was that 1337 has a different highlight by default when you define functions:

![Function Definition](http://i.imgur.com/ODVNk7k.png)

Not sure if that matters in the case you mentioned, just wanted to clear things up. Otherwise, italic/non-italic separation could work for me, if it's the easiest.

**Comment by abusalimov** [comment]
Unfortunately, I don't have much spare time now (neither did I on last weekend), sorry. I'll return to this as soon as possible.

**Comment by abusalimov** [comment]
Hi, @kgizdov 

Finally, this issue is completely resolved. You can catch up all recent fixes and enhancements by updating to v1.7.0 (will arrive to Package Control soon).

This took too long to finish, sorry for that, but better late that never, after all. I would be happy to hear your feedback, particularly on the improved highlighting of float literals.

**Comment by kgizdov** [comment]
I think it looks pretty good. Thank you for taking the time. The float literals are correctly identified and highlighted. The only thing, which I kinda liked, but might not appeal to everyone is that the numbers in the literals are highlighted differently from the letters. I actually kinda see it as a further differentiation step, but might be too much colour for some people. As far as I am concerned it's good now, but if you think that might be an issue, you may want to consider changing it. Thanks a lot for the effort and keep up the good work.

**Comment by abusalimov** [comment]
You're very welcome and thank you for the feedback.

Well, I thought about that, but decided to only highlight "special" letters (like the `0x` suffix, `UL` prefixes or the exponent sign), and left significant numbers untouched. In this sense, hexadecimal letters (`[a-f]`) are not distinguished from decimal numbers.

Here's a highlighted fragment from `test_numbers.c` file:
![sublime-c-improved-numbers](https://cloud.githubusercontent.com/assets/530396/10732191/fbfc716a-7c09-11e5-8abb-eeb57aff952c.png)
