### ISSUE TITLE
Include directive miscolored when preceded by single-line comment

### ISSUE THREAD

**Issue by nslogan** [abusalimov/SublimeCImproved#18]
Example:
```c
#include <sys/neutrino.h>	// Comment
#include <sys/mman.h>		// Comment
```

In the above example, the first `#include` would be my normal syntax color but the second `#include` is a different color. If I use a multi-line comment, `/* ... */`, syntax coloring is normal for both directives.

I'm on: Windows 7, ST3 Build 3083

**Comment by abusalimov** [comment]
Thanks for reporting this, I was able to reproduce it.
I'm on a journey now, but I hope I'll be able to see what I can do about this next week.
