### ISSUE TITLE
unable to find namespace functions

### ISSUE THREAD

**Issue by JohannesMP** [abusalimov/SublimeCImproved#21]
I installed sublime C improved to improve the `Go To Definition...` behavior with c++ in Sublime Text 3. I'm not sure if this package handles this issue, and if not please do let me know.

I noticed that when I have a function declared in a namespace, such as in a class or an explicit namespace, `Go To Definition...` does not work. For example:

    #include <iostream>

    namespace foo
    {
      int bar() { return 123; }
    }

    int main(int argc, char const *argv[])
    {
      std::cout << foo::bar() << std::endl;
      return 0;
    }

Putting the cursor on `bar` in the main function and pressing f12 (or choosing `Go To Definition...` from the menu) will result in the status bar saying `Unable to find bar`:
![screenshot_2015-09-13_22 20 50](https://cloud.githubusercontent.com/assets/662874/9842660/b7bb68b4-5a65-11e5-84b4-9a31e49b7f85.png)
Should this work? Is there any way I can get sublime text 3 to jump to definitions inside of classes or namespaces, either with this package or another?

**Comment by abusalimov** [comment]
Hi,

Thanks for reporting this, and sorry for the late response - I'm on vacation now.

If I'm not mistaken, I didn't change C++-related stuff too much; behavior of this particular feature should be the same as for the standard C/C++ Sublime package.

Anyway, *Go To Definition* in Sublime is rather dumb: it doesn't understand nested contexts, e.g. namespaces. And there's nothing I can do with this.

I guess, it is designed to work for cases when a definition contains a qualified name, e.g. `int foo::bar() { ... }`.
