### ISSUE TITLE
Multi-line function declarations are indexed as function definitions

### ISSUE THREAD

**Issue by jaytiar** [abusalimov/SublimeCImproved#26]
I think I've found another small bug in your excellent syntax definition.

Looks like multi-line function forward declarations are getting picked up as function definitions by mistake. Single-line declarations seem to work okay.

So:
Broken:
```
int dec_stats(void *,
              int,
              int);
```
Works:
```
int dec_stats(void *, int, int);
```
Would be great if you could take a look when you have a moment.
Thanks!

**Comment by abusalimov** [comment]
Thanks for reporting this!

That's how Sublime Text works. In a nutshell, it parses a source file line-by-line, using regexes defined in a tmLanguage file. That is, at the moment of handling the first line ...
```c
int dec_stats(void *,
```
... there's no way to tell what is going to appear next, just a declaration, or a complete definition.
C Improved falls back to interpreting these cases as definitions, which of course may give false positives, but then you won't miss real definitions.

Unfortunately there nothing we can do with it, this is a known issue, sorry for that. FWIW, it's also similar to #12 and #3.
