### ISSUE TITLE
Support for function definition arguments on second line

### ISSUE THREAD

**Issue by jmclaughlan** [abusalimov/SublimeCImproved#3]
We use a coding standard that puts the arguments on the lines below the function definition:

``` c
static void my_func
(
  void
)
{
}
```

Which isn't recognized by ST3/CImproved as a function, isn't color highlighted and does not show up in ctrl-r or ctrl-shift-r list.

I see that all that is needed to make it a "function" is to place at least the opening parenthesis on the same line as the function name.  In C it should not matter how many spaces or lines are in between and should be considered as white space.

This may be an issue with the C/C++ syntax as built into ST3 but I was hoping that it could be handled in CImproved.

**Comment by dwhall** [comment]
abusalimov, I understand your reason for "wontfix" on this issue.  I wish the ST authors could fix this issue, not for syntax highlight/coloring but because I can't do Ctrl+R (Goto symbol) on C function names.

**Comment by abusalimov** [comment]
BTW, there're some related requests on userecho: for example, [API for language syntax](https://sublimetext.userecho.com/topic/106458-api-for-language-syntax/) and [Plugin API request](https://sublimetext.userecho.com/topic/117845-plugin-api-request/), both created over 3 years ago though...
