### ISSUE TITLE
Function declarations with parameters on different lines

### ISSUE THREAD

**Issue by fatdollar** [abusalimov/SublimeCImproved#38]
I've tried and tried but I can't figure out how to add this functionality to the syntax highlighting.

what is want is this:
```c
int main
(int argc, char const *argv[])
```

to be recognized as a function just like this is
```c
int main(int argc, char const *argv[])
```

It doesn't sound hard but I don't understand how these tmLanguage file work. and any time I look in to regular expressions it leaves me confused and more stupid.

Thanks.

**Comment by abusalimov** [comment]
Yeah, it might seem pretty easy at first glance, but it is in fact impossible to make it work more or less reliably, unfortunately. This is because of how tmLanguage grammar engine works, you might want to read #3 and #12 for the explanation.
