### ISSUE TITLE
Using preprocessor inside of parameter list causes improper "mismatched parentheses" flag

### ISSUE THREAD

**Issue by woodrowbarlow** [abusalimov/SublimeCImproved#43]
``` c
int main(void) {
    my_function (1, 2, 3,
#ifdef DEBUG
                 "hard/coded/path");
#else
                 path);
#endif
}
```

The last closing parentheses (after `path`, but not after `"hard/coded/path"`) is marked as if it were mismatched. As a side effect, the closing brace on the scope also gets imporoperly flagged as mismatched.

This doesn't appear to be a bug in your package (since the same thing happens when it is disabled), but I think it falls squarely into the wheelhouse of problems you are trying to solve.

Thanks for creating a great package!

**Comment by woodrowbarlow** [comment]
my mistake... my editor was using the default C parser. when using C-Improved, it works as it should!

**Comment by abusalimov** [comment]
@woodrowbarlow for some reason my initial reply is shown here as an editable draft, that is it was not posted right away after I have written it. Weird. Sorry for the late response then, posting it anyway:

> Thank you for the kind words!
> 
> I've been thinking about how to solve that long time ago and didn't come up with a reasonable solution, alas. The problem is that from the point of view of Sublime this is indeed a piece of code with unbalanced parentheses. There's no way to teach it to parse each preprocessor branch separately. At best, one could make it consider only the truth branch of `#if` conditionals and don't check balance of the rest branches, but I'm afraid the possible solution would be rather fragile.
> 
> Thanks for reporting the issue anyway. I wish one day this could be fixed in a more graceful way.

I'm glad to hear this is not the issue for you after all. Although I'd expect the piece of code in question to confuse Sublime anyway, yet it may not be highlighted as an error depending on the parser.
