### ISSUE TITLE
Syntax highlighting loses scope with macros

### ISSUE THREAD

**Issue by digikata** [abusalimov/SublimeCImproved#52]
The following code has C Improved highlighting lose track of braces (works with default sublime C mode syntax highlighting):

```
int function1(int a, int b)
{
#ifdef CONFIG_SOMETHING
	if (a) {
#else
	if (b) {
#endif
		// do a thing
	}
	return 0;
}

// C Improved misses this highlight as a function
void function2(int c)
{
}
```

**Comment by digikata** [comment]
nvm looks like a retired repo

**Comment by abusalimov** [comment]
> nvm looks like a retired repo

Yeah, sorry for that

**Comment by digikata** [comment]
No worries, thanks for working on C improved and posting it in the first place
